[package]
name = "rustfmt-bug"
version = "0.1.0"
authors = ["Markus Westerlind <markus.westerlind@distilnetworks.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[test]]
name = "test"
harness = false
